import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header/header";
import { cn } from "@/lib/utils";
import ThemeProvider from "@/lib/providers/theme-provider";
import { BackgroundBeams } from "@/components/ui/background-beams";

const inter = Poppins({
    subsets: ["latin"],
    weight: "500",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn(inter.className)}>
                {process.env.NODE_ENV === "development" ? null : (
                    <BackgroundBeams />
                )}
                <ThemeProvider>
                    <Header />
                    <main className="container">{children}</main>
                </ThemeProvider>
            </body>
        </html>
    );
}
